version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    ports:
      - "2181:2181"
    networks:
      - kafka
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    ports:
      - "9092:9092"
    networks:
      kafka:
        ipv4_address: 172.18.0.3
        aliases:
          - kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_CREATE_TOPICS: "test:1:1"

networks:
  kafka:
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24
